using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
using System.Globalization;
using Handy.Lib;
using System.Threading;

namespace Handy
{
    public partial class InventoryProcessingWindow_Symbol : BaseWindow
    {
        #region Variables

        private Int32 Count = 0;
        private CommonEnum.Buttons ExitButton = CommonEnum.Buttons.Exit;
        private DataTable MIT = new DataTable();
        private bool EditQty = false;
        private string ScannedQty = "0";
        private string tempLocator = string.Empty;
        private ActivateWindow ActivatedWindow = ActivateWindow.Generate;
        private enum ActivateWindow
        { 
            Save,
            Generate,
            Renew,
            Ok,
            View,
            ViewNotYetApproved
        }

        #endregion

        #region Constructors

        public InventoryProcessingWindow_Symbol(BarcodeReader BCReader, ReaderData BCData)
        {
            InitializeComponent();
            base.SetBarcodeReader(BCReader, BCData);
            base.SetWindowTitle("Inventory Processing");
            base.SetActiveButtons(BaseButtons.Generate, BaseButtons.Cancel);
            CommonInterfaceFunctions.WLANAddSignalQualityHandler(base.pcbSignal, true);
        }

        #endregion

        #region Functions

        private void SetGenericDisplay()
        {
            this.lblGenerateHeader.BackColor = System.Drawing.Color.Teal;
            this.labelnote.BackColor = System.Drawing.Color.Teal;
            this.lblScannedCountBack.BackColor = System.Drawing.Color.Teal;
            this.panelGenerationInfo.Location = new System.Drawing.Point(3, 38);
            this.panelGenerationInfo.Size = new System.Drawing.Size(313, 242);
        }
        
        private void SetGenerationPanelDisplay()
        {
            InventoryBase.IsInventoryProcess = true;
            if (CommonFunctions.InventoryMaster != null)
            {
                if (CommonFunctions.InventoryMaster.Rows.Count > 0)
                {
                    this.lblDateGenerated.Text = String.Format("Date Generated : {0}", CommonFunctions.GeneratedDate);
                    this.lblGeneratedby.Text = String.Format("Generated By : {0}", CommonFunctions.GeneratedBy);
                    this.lblRows.Text = String.Format("Row(s) : {0}", CommonFunctions.GeneratedRowCnt);
                    this.ActivatedWindow = ActivateWindow.Renew;
                    base.SetActiveButtons(BaseButtons.Renew, BaseButtons.Cancel);
                }
            }
        }
        
        private void SetDisposablePendingTable()
        {
            CommonFunctions.DisposableTable = new DataTable();
            CommonFunctions.DisposableTable.Columns.Add("RRNoDisplay", typeof(String));
            CommonFunctions.DisposableTable.AcceptChanges();
        }

        private void SetInventoryCountDisplay()
        {
            int[] Counts = new int[3];
            Counts = InventoryBase.ListCount(CommonEnum.Function.Inventory);
            this.lblScannedCount.Text = Convert.ToString(Counts[0] + Counts[1]);
            this.lblPending.Text = Convert.ToString(Counts[0]);
            //Releasing
            Counts = null;
        }

        private void ShowItemScanned(bool Edited)
        {
            if (ActivatedWindow == ActivateWindow.Save)
            {
                if (Edited)
                    this.lblPopupScanStatus.Text = "Item Saved";
                else
                    this.lblPopupScanStatus.Text = "Item Scanned";
                this.lblPopupScanStatus.Visible = true;
                pcbCheckIcon.Visible = true;
                tmrDisplayCheck.Enabled = true;
                tmrDisplayCheck.Interval = 4000;
            }
            else 
            {
                lblPopupScanStatus.Visible = true;
                pcbCheckIcon.Visible = true;
                tmrDisplayCheck.Enabled = true;
                tmrDisplayCheck.Interval = 4000;
            }
          
        }

        private void HideCheckedIcon()
        {
            lblPopupScanStatus.Visible = false;
            pcbCheckIcon.Visible = false;
            pcbCheckIcon.Visible = false;
        }

        private void GetInventoryRRInfo()
        {
            //Clear info
            InventoryBase.Reprint = false;
            CommonFunctions.lblThreadingDisplay = this.lblWarning;
            CommonFunctions.TagNo = string.Empty;
            CommonFunctions.OldLocatorCode = string.Empty;
            CommonFunctions.AvailableQty = 0;
            CommonFunctions.ExpectedActualQty = CommonFunctions.ConvertStringDecimal(string.IsNullOrEmpty(CommonFunctions.BarcodeQuantity) ? "0" : CommonFunctions.BarcodeQuantity);
            CommonFunctions.Unit = "";
            //Check if reference is generated
            if (!CommonFunctions.InventoryReferenceGenerated)
            {
                //Cursor.Current = Cursors.Default;
                CommonFunctions.MessageShow(CommonMsg.Warning.d_DownloadInventoryReference, CommonEnum.NotificationType.Warning);
                return;
            }
            //Get RR Details
            if (!CommonFunctions.IsInventoryRRinfoGenerated())
            {
                //Label is not latest
                CommonFunctions.TagNo = CommonMsg.Info.BarcodeObsolete;
                CommonFunctions.Unit = CommonMsg.Info.UnitNotApplicable;
                CommonFunctions.AvailableQty = 0;
                CommonFunctions.OldLocatorCode = CommonMsg.Info.LocatorUndefined;
                CommonFunctions.ValidityType = CommonEnum.GetStringValue(CommonEnum.ValidityType.ForProcessing);
                CommonFunctions._Remark = CommonMsg.Info.InventrySubjectForReprocessing;
            }
            if (CommonFunctions.BarcodeQuantity == string.Empty || CommonFunctions.BarcodeQuantity == "0")
            {
                CommonFunctions.MessageShow(CommonMsg.Warning.NoQty, CommonEnum.NotificationType.Warning);
            }
            //Set interface
            this.TagNo.Text = CommonFunctions.TagNo;
            if (this.TagNo.Text.Equals(CommonMsg.Info.BarcodeObsolete))
                this.TagNo.BackColor = System.Drawing.Color.Red;
            else
                this.TagNo.BackColor = System.Drawing.Color.White;

            this.RRNo.Text = CommonFunctions.RRNoDisplay;
            this.BalanceQty.Text = String.Format("{0:0.00}", CommonFunctions.AvailableQty);
            this.UnitBalance.Text = CommonFunctions.Unit;
            this.PrintedQty.Text = CommonFunctions.BarcodeQuantity;
            this.UnitPrinted.Text = CommonFunctions.Unit;
            this.ExitButton = CommonEnum.Buttons.Cancel;
            this.ScannedQty = CommonFunctions.BarcodeQuantity;
            //Auto Saving 
            this.SaveLocal(false);
            //Resume interface
            base.BarcodeReader_Start();
            this.PrintedQty.Focus();
            this.PrintedQty.SelectAll();
        }

        private void SaveLocal(bool Edited)
        {
            string AddQuery = String.Empty;

            string UpdateQuery = String.Empty;

            AddQuery = string.Format(CommonQueryStrings.Mobile.Insert.Inventory
                                        , CommonFunctions.BarcodeRRNo
                                        , CommonFunctions.BarcodeRRSeq
                                        , CommonFunctions.BarcodeRRLotSeq
                                        , CommonFunctions.BarcodeRRLocSeq
                                        , CommonFunctions.BarcodeStockCode
                                        , CommonFunctions.BarcodePrintedDate
                                        , CommonFunctions.TagNo
                                        , CommonFunctions.OldLocatorCode
                                        , CommonFunctions.LocatorCode
                                        , CommonFunctions.LocatorDesc
                                        , CommonFunctions.AvailableQty        //WarehouseBalanceQty
                                        , CommonFunctions.ExpectedActualQty   //WarehouseInventoryQty
                                        , CommonFunctions.Unit
                                        , CommonFunctions.GetDateTime() //sentdate
                                        , Edited == true ? "T" : "F"
                                        , CommonFunctions._Remark //remark
                                        , "1"           //scanflag
                                        , "0"           //sentflag
                                        , CommonFunctions.ValidityType
                                        );

            UpdateQuery = string.Format(CommonQueryStrings.Mobile.Update.Inventory
                                        , CommonFunctions.BarcodeRRNo
                                        , CommonFunctions.BarcodeRRSeq
                                        , CommonFunctions.BarcodeRRLotSeq
                                        , CommonFunctions.BarcodeRRLocSeq
                                        , CommonFunctions.BarcodeStockCode
                                        , CommonFunctions.BarcodePrintedDate
                                        , CommonFunctions.TagNo
                                        , CommonFunctions.OldLocatorCode
                                        , CommonFunctions.LocatorCode
                                        , CommonFunctions.LocatorDesc
                                        , CommonFunctions.AvailableQty
                                        , CommonFunctions.ExpectedActualQty
                                        , CommonFunctions.Unit
                                        , CommonFunctions.GetDateTime()  //sentdate
                                        , Edited == true ? "T" : "F"
                                        , CommonFunctions._Remark //remark
                                        , "1"           //scanflag
                                        , "0"           //sentflag
                                        , CommonFunctions.ValidityType);

            if (InventoryBase.MobiledbInventoryProcess(AddQuery, UpdateQuery))
            {
                //this.ShowItemScanned(Edited); //Process not approved yet
                //this.SetDisposablePendingTable();
                this.SetInventoryCountDisplay();
                try
                {
                    if (!this.lblPending.Text.Equals("0"))
                    {
                        if (Convert.ToInt32(this.lblPending.Text) % 50 == 0)
                            CommonFunctions.MessageShow(String.Format(CommonMsg.Warning.d_PendingMaxCountWarning, this.lblPending.Text), CommonEnum.NotificationType.Warning);
                    }
                }
                catch { }
                //CommonFunctions.MessageShow(CommonMsg.Success.d_LocalSave + string.Format(CommonMsg.Info.d_RRCommonInfo, CommonFunctions.RRNoDisplay, CommonFunctions.BarcodeStockCode, Qty), CommonEnum.NotificationType.Sucess);
            }
            else
                CommonFunctions.MessageShow(CommonMsg.Error.d_Unsave);

            #region Textfile Writting Commented Code
            /**Nilo Commented 20130617 : to increase speed.**/
            //Write Text File for back up.
            //try
            //{
            //    #region Text Parameter Info
            //    TextParameterInfo[] TextParamInfo = new TextParameterInfo[13];
            //    TextParamInfo[0] = new TextParameterInfo("POSTED", CommonEnum.GetStringValue(CommonEnum.UploadStats.Pending));
            //    TextParamInfo[1] = new TextParameterInfo("TAGNO", CommonFunctions.TagNo);
            //    TextParamInfo[2] = new TextParameterInfo("RRNODISPLAY", CommonFunctions.RRNoDisplay);
            //    TextParamInfo[3] = new TextParameterInfo("OLDLOCATORCODE", CommonFunctions.OldLocatorCode);
            //    TextParamInfo[4] = new TextParameterInfo("INVENTORYLOCATORCODE", CommonFunctions.LocatorCode);
            //    TextParamInfo[5] = new TextParameterInfo("INVENTORYLOCATORDESC", CommonFunctions.LocatorDesc);
            //    TextParamInfo[6] = new TextParameterInfo("BALANCEQTY", CommonFunctions.AvailableQty.ToString().Trim());
            //    TextParamInfo[7] = new TextParameterInfo("ACTUALQTY", PrintedQty.Text.Trim());
            //    TextParamInfo[8] = new TextParameterInfo("UNIT", CommonFunctions.Unit);
            //    TextParamInfo[9] = new TextParameterInfo("SENTDATETIME", "");
            //    TextParamInfo[10] = new TextParameterInfo("REMARK", "UNSENT");
            //    TextParamInfo[11] = new TextParameterInfo("TRANSACTED", Edited == true ? "T" : "F");
            //    TextParamInfo[12] = new TextParameterInfo("BARCODEDATE", CommonFunctions.BarcodePrintedDate);
            //    #endregion

            //    bool append = Logger.isFileExist(Logger.HandyPath, Logger.HandyMITFile);
            //    Logger.WriteTextData(Logger.HandyPath, Logger.HandyMITFile, TextParamInfo, true, append, '~');
            //}
            //catch
            //{ }
            /**End Comment**/
            #endregion

        }

        private void SaveButton(object sender, EventArgs e)
        {

            if (CommonFunctions.ConvertStringDecimal(this.ScannedQty) != CommonFunctions.ConvertStringDecimal(this.PrintedQty.Text)
                && this.PrintedQty.ReadOnly != true)
            {
                if (this.PrintedQty.Text.Trim() == string.Empty)
                {
                    CommonFunctions.MessageShow(CommonMsg.Warning.NoQty, CommonEnum.NotificationType.Warning); //REFRESH COUNT
                    return;
                }

                if (!string.IsNullOrEmpty(this.RRNo.Text) && !string.IsNullOrEmpty(CommonFunctions.RRNoDisplay))
                {
                    CommonFunctions.ExpectedActualQty = CommonFunctions.ConvertStringDecimal(PrintedQty.Text);
                    this.SaveLocal(true);
                    this.ActivatedWindow = ActivateWindow.View;
                    //CommonInterfaceFunctions.FormatFooterPicture(this.pbFooter, Properties.Resources.FooterView); //Process not yet approved
                    base.SetActiveButtons(BaseButtons.Save, BaseButtons.Cancel);

                }
                else
                    this.PrintedQty.Text = string.Empty;
                this.EditQty = false;
                this.PrintedQty.ReadOnly = true;
            }
        }

        private void Generate(object sender, EventArgs e)
        {
            CommonFunctions.lblThreadingDisplay = this.lblWarning;
            if (this.ActivatedWindow == ActivateWindow.Ok)
            {
                this.panelGenerationInfo.Visible = false;
                this.ActivatedWindow = ActivateWindow.View;
                //CommonInterfaceFunctions.FormatFooterPicture(this.pbFooter, Properties.Resources.FooterView); //Process not yet approved
                base.SetActiveButtons(BaseButtons.Save, BaseButtons.Cancel);
                return;
            }
            if (InventoryBase.MobiledbGenerateInventoryReferenceList())
            {
                this.lblDateGenerated.Text = String.Format("Date Generated : {0}", CommonFunctions.GeneratedDate);
                this.lblGeneratedby.Text = String.Format("Generated By : {0}", CommonFunctions.GeneratedBy);
                this.lblRows.Text = String.Format("Row(s) : {0}", CommonFunctions.GeneratedRowCnt);
                if (CommonFunctions.InventoryMaster == null)
                {
                    this.ActivatedWindow = ActivateWindow.Generate;
                    base.SetActiveButtons(BaseButtons.Generate, BaseButtons.Cancel);
                }
                else
                {
                    this.ActivatedWindow = ActivateWindow.Ok;
                    base.SetActiveButtons(BaseButtons.Ok, BaseButtons.Cancel);
                }
            }
            else
            {
                if (CommonFunctions.InventoryMaster == null)
                {
                    CommonFunctions.MessageShow(CommonMsg.Warning.d_UnableGenMITMaster, CommonEnum.NotificationType.Warning);
                }
                else
                {
                    CommonFunctions.MessageShow(CommonMsg.Warning.d_UnableRefreshMITMaster, CommonEnum.NotificationType.Warning);
                }
            }
        }

        private void CancelButton(object sender, EventArgs e)
        {
            if (this.ExitButton == CommonEnum.Buttons.Cancel)
            {
                this.ClearAll();
                this.ExitButton = CommonEnum.Buttons.Exit;
                //CommonInterfaceFunctions.FormatFooterPicture(this.pbFooter, Properties.Resources.FooterView); //Process not yet approved
                base.SetActiveButtons(BaseButtons.Save, BaseButtons.Cancel);
                this.PrintedQty.Focus();
                base.BarcodeReader_Start();
                this.ActivatedWindow = ActivateWindow.View;
            }
            else
            {
                string Pending = CommonFunctions.CEDataReader(CommonQueryStrings.Mobile.View.InventoryPendingCount);
                if (!Pending.Trim().Equals("0"))
                {
                    if (DialogResult.Yes == CommonFunctions.MessageShow(CommonMsg.Warning.d_PendingWarning, CommonEnum.NotificationType.Question, CommonEnum.MessageButtons.YesNo))
                    {
                        this.ClosingWindow();
                    }
                }
                else
                {
                    this.ClosingWindow();
                }
            }

        }

        private void ClosingWindow()
        {
            CommonFunctions.RRNo = "";
            CommonFunctions.LocatorCode = "";
            CommonFunctions.LocatorDesc = "";
            CommonFunctions.IsProcessing = false;
            InventoryBase.IsInventoryProcess = false;
            CommonFunctions.ClearStrings();
            try
            {
                this.tmrDisplayCheck.Enabled = false;
                this.tmrDisplayCheck.Dispose();
            }
            catch { }
            this.Close();
        }

        private void RefreshCount(object sende, EventArgs e)
        {
            //if (InventoryBase.ListCount(CommonEnum.Function.Inventory)[0] > 0)
            //{
            //    CommonFunctions.MessageShow(CommonMsg.Warning.d_UnabletoRefreshScannedCount, CommonEnum.NotificationType.Warning);
            //    return;
            //}
            if (DialogResult.Yes == CommonFunctions.MessageShow(CommonMsg.Warning.d_RefreshInventoryCount, CommonEnum.NotificationType.Question, CommonEnum.MessageButtons.YesNo))
            {
                CommonFunctions.CeExecuteNonQuery(CommonQueryStrings.Mobile.Delete.InventoryScannedCount);
                this.lblScannedCount.Text = "0";
            }
        }

        private void ClearAll()
        {
            //Commmon
            this.TagNo.Text = "";
            this.RRNo.Text = "";
            this.BalanceQty.Text = "";
            this.UnitBalance.Text = "";
            this.PrintedQty.Text = "";
            this.UnitPrinted.Text = "";
            this.ScannedQty = "0";
            this.TagNo.BackColor = System.Drawing.Color.White;
            CommonFunctions.ClearStrings();
            lblPopupScanStatus.Visible = false;
            pcbCheckIcon.Visible = false;
        }

        public void Inventorylist()
        {
            #region Load List

            base.BarcodeReader_Stop();
            try
            {
                this.TagNo.BackColor = System.Drawing.Color.White;
                this.RRNo.Text = "";
                this.TagNo.Text = "";
                this.BalanceQty.Text = "";
                this.PrintedQty.Text = "";
                this.UnitBalance.Text = "";
                this.UnitPrinted.Text = "";
                CommonFunctions.RRNo = "";
                lblPopupScanStatus.Visible = false;
                pcbCheckIcon.Visible = false;
                InventoryListWindow _InventoryListWindow = new InventoryListWindow();
                _InventoryListWindow.ShowDialog();
                CommonInterfaceFunctions.WLANAddSignalQualityHandler(base.pcbSignal, true);
                //this.SetDisposablePendingTable();
                this.SetInventoryCountDisplay();
            }
            catch (Exception err)
            { CommonFunctions.MessageShow(err.Message, CommonEnum.NotificationType.Warning); }
            base.BarcodeReader_Start();

            #endregion
        }

        #endregion

        #region Overrides

        protected override void BarcodeReader_AnalyzeType(object Sender, EventArgs e)
        {
            base.BarcodeReader_AnalyzeType(Sender, e);
        
            switch (base.ScannedBarcodeType)
            {
                case CommonEnum.LabelType.Item2D:
                    {
                        if (string.IsNullOrEmpty(CommonFunctions.LocatorCode))
                        {
                            CommonFunctions.MessageShow(CommonMsg.Warning.ScanLocator, CommonEnum.NotificationType.Warning);
                            this.ClearAll();
                            base.BarcodeReader_Start();

                        }
                        else
                        {
                            //DateTime start = DateTime.Now;
                            //Cursor.Current = Cursors.WaitCursor;
                            this.EditQty = false;
                            this.PrintedQty.ReadOnly = true;
                            //CommonInterfaceFunctions.FormatFooterPicture(this.pbFooter, Properties.Resources.FooterView); //Process not yet approved
                            base.SetActiveButtons(BaseButtons.Save, BaseButtons.Cancel);
                            this.GetInventoryRRInfo();
                            this.PrintedQty.Focus();
                            //Cursor.Current = Cursors.Default;
                            //TimeSpan timeItTook = DateTime.Now - start;
                            //this.lblTime.Text = string.Format(lblTime.Text, timeItTook);
                        }
                    }
                    break;
                case CommonEnum.LabelType.ItemLinear:
                    {
                        if (!string.IsNullOrEmpty(CommonFunctions.LocatorCode))
                            CommonFunctions.MessageShow(String.Format(CommonMsg.Info.InventoryLocator, CommonFunctions.LocatorDesc));
                        else
                        {
                            CommonFunctions.MessageShow(CommonMsg.Warning.ScanLocator, CommonEnum.NotificationType.Warning);
                            this.ClearAll();
                            base.BarcodeReader_Start();
                        }
                    }
                    break;
                case CommonEnum.LabelType.Invalid:
                    {
                        this.ClearAll();
                        this.LocatorCodeDesc.Text = "";
                        this.LocatorCode.Text = "";
                        this.LocatorCode.Focus();
                        this.LocatorCode.SelectAll();
                        base.BarcodeReader_Start();
                    }
                    break;
                case CommonEnum.LabelType.LocatorCode:
                    {
                        this.ClearAll();
                        this.LocatorCode.Text = CommonFunctions.LocatorCode;
                        this.LocatorCodeDesc.Text = CommonFunctions.LocatorDesc;
                        CommonFunctions.MessageShow(String.Format(CommonMsg.Info.InventoryLocator, CommonFunctions.LocatorDesc));
                        this.PrintedQty.Focus();
                        base.BarcodeReader_Start();
                    }
                    break;
                case CommonEnum.LabelType.ServerNotFound:
                    {
                        this.ClearAll();
                        this.LocatorCodeDesc.Text = "";
                        this.LocatorCode.Text = "";
                        this.LocatorCode.Focus();
                        base.BarcodeReader_Start();
                    }
                    break;
            }

            base.ScannedBarcodeType = CommonEnum.LabelType.Null;
        }

        protected override void BaseWindow_KeyUp(object sender, KeyEventArgs e)
        {
            switch (e.KeyCode)
            {
                case Keys.Left:
                    if (PrintedQty.Text != "" && BalanceQty.Text != "")
                    {
                        base.SetActiveButtons(BaseButtons.Save, BaseButtons.Cancel);
                        this.ActivatedWindow = ActivateWindow.Save;
                        this.EditQty = true;
                        this.PrintedQty.ReadOnly = false;
                        this.PrintedQty.Focus();
                        this.PrintedQty.SelectAll();
                        CommonFunctions.ParseRRNoDisplay(this.RRNo.Text);
                    }
                    else
                    {
                        //CommonInterfaceFunctions.FormatFooterPicture(this.pbFooter, Properties.Resources.FooterView); //Process not yet approved
                        base.SetActiveButtons(BaseButtons.Save, BaseButtons.Cancel);
                        this.EditQty = false;
                        this.PrintedQty.ReadOnly = true;
                        this.PrintedQty.Focus();
                        this.ActivatedWindow = ActivateWindow.View;
                    }
                    break;
                case Keys.F1:

                    if (this.ActivatedWindow == ActivateWindow.ViewNotYetApproved) //Process not yet approved
                    {
                        this.Inventorylist();
                    }
                    else if (this.ActivatedWindow == ActivateWindow.Save 
                          || this.ActivatedWindow == ActivateWindow.View) //Process not yet approved
                    {
                        this.SaveButton(this, e);
                    }
                    else
                    {
                        this.Generate(this, e);
                    }
                    break;
                case Keys.Enter:
                    {
                        this.Inventorylist();
                    }
                    break;
                case Keys.F4:
                    if (this.panelGenerationInfo.Visible == true)
                    {
                        this.panelGenerationInfo.Visible = false;
                        this.ActivatedWindow = ActivateWindow.View;
                        //CommonInterfaceFunctions.FormatFooterPicture(this.pbFooter, Properties.Resources.FooterView); //Process not yet approved
                        base.SetActiveButtons(BaseButtons.Save, BaseButtons.Cancel);
                    }
                    else
                        this.CancelButton(this, e);
                        
                    break;
                case Keys.Space:
                    this.RefreshCount(this, e);
                    break;
            }

            base.BaseWindow_KeyUp(sender, e);
        }

        protected override void lblBtnRight_Click(object sender, EventArgs e)
        {
            KeyEventArgs KeyArgs = new KeyEventArgs(Keys.F15);
            this.BaseWindow_KeyUp(sender, KeyArgs);
        }

        protected override void lblBtnLeft_Click(object sender, EventArgs e)
        {
            KeyEventArgs KeyArgs = new KeyEventArgs(Keys.F14);
            this.BaseWindow_KeyUp(sender, KeyArgs);
        }

        #endregion

        //Events

        private void timer1_Tick(object sender, EventArgs e)
        {
            this.HideCheckedIcon();
            tmrDisplayCheck.Enabled = false;
        }

        private void InventoryProcessing_Load(object sender, EventArgs e)
        {
            this.SetGenericDisplay();
            this.SetGenerationPanelDisplay();
            this.SetInventoryCountDisplay();
            this.PrintedQty.Focus();
        }

        private void PrintedQty_KeyPress(object sender, KeyPressEventArgs e)
        {
            NumberFormatInfo numberFormatInfo = CultureInfo.CurrentCulture.NumberFormat;
            string decimalSeparator = numberFormatInfo.NumberDecimalSeparator;

            string keyInput = e.KeyChar.ToString();

            if ((!CommonFunctions.isDecimal()) && (Char.IsDigit(e.KeyChar) || e.KeyChar == '\b'))
                e.Handled = false;
            else if ((CommonFunctions.isDecimal()) && (Char.IsDigit(e.KeyChar) || keyInput.Equals(decimalSeparator) || e.KeyChar == '\b'))
                if (PrintedQty.Text.IndexOf('.') != -1)
                    //allows digit and backspace
                    if (Char.IsDigit(e.KeyChar) || e.KeyChar == '\b')
                        e.Handled = false;
                    else
                        e.Handled = true;
                else
                    e.Handled = false;
            else
                e.Handled = true;
        }
        
    }
}