//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8669.
// 
namespace HandyUpdater.UpdaterWebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UpdaterWebServiceSoap", Namespace="http://localhost/Handy/UpdaterWebService.asmx")]
    public partial class UpdaterWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UpdaterWebService() {
            this.Url = "http://localhost:81/Handy/UpdaterWebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Handy/UpdaterWebService.asmx/GetUpdateInfo", RequestNamespace="http://localhost/Handy/UpdaterWebService.asmx", ResponseNamespace="http://localhost/Handy/UpdaterWebService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateInfo GetUpdateInfo(string name, int major, int minor, int build, int revision) {
            object[] results = this.Invoke("GetUpdateInfo", new object[] {
                        name,
                        major,
                        minor,
                        build,
                        revision});
            return ((UpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUpdateInfo(string name, int major, int minor, int build, int revision, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUpdateInfo", new object[] {
                        name,
                        major,
                        minor,
                        build,
                        revision}, callback, asyncState);
        }
        
        /// <remarks/>
        public UpdateInfo EndGetUpdateInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UpdateInfo)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/Handy/UpdaterWebService.asmx")]
    public partial class UpdateInfo {
        
        private string urlField;
        
        private bool isAvailableField;
        
        private string newVersionField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAvailable {
            get {
                return this.isAvailableField;
            }
            set {
                this.isAvailableField = value;
            }
        }
        
        /// <remarks/>
        public string newVersion {
            get {
                return this.newVersionField;
            }
            set {
                this.newVersionField = value;
            }
        }
    }
}
