//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Handy.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim Mode ....
        /// </summary>
        internal static string AimMode {
            get {
                return ResourceManager.GetString("AimMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim Type ....
        /// </summary>
        internal static string AimType {
            get {
                return ResourceManager.GetString("AimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;ERPDB&quot; value=&quot;Data Source=192.168.135.50; Initial Catalog=EHS;Persist Security Info=True;User ID=sa;Password=systemadmin&quot; /&gt;
        ///    &lt;add key=&quot;HandyDB&quot; value=&quot;Data Source=Temp\HandyDB.sdf; LCID=1033; Password=systemadmin; Encrypt=true&quot; /&gt;
        ///  &lt;/appSettings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string App_bak_config {
            get {
                return ResourceManager.GetString("App_bak_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;ERPDB&quot; value=&quot;Data Source=192.168.135.50; Initial Catalog=EHS;Persist Security Info=True;User ID=sa;Password=systemadmin&quot; /&gt;
        ///    &lt;add key=&quot;HandyDB&quot; value=&quot;Data Source=Temp\HandyDB.sdf; LCID=1033; Password=systemadmin; Encrypt=true&quot; /&gt;
        ///  &lt;/appSettings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string App_config {
            get {
                return ResourceManager.GetString("App_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit..
        /// </summary>
        internal static string AppExitMsg {
            get {
                return ResourceManager.GetString("AppExitMsg", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Battery_ACConnected {
            get {
                object obj = ResourceManager.GetObject("Battery_ACConnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_High {
            get {
                object obj = ResourceManager.GetObject("Battery_High", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_Low {
            get {
                object obj = ResourceManager.GetObject("Battery_Low", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_Medium {
            get {
                object obj = ResourceManager.GetObject("Battery_Medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Battery_VeryLow {
            get {
                object obj = ResourceManager.GetObject("Battery_VeryLow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.15.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code128 ....
        /// </summary>
        internal static string Code128 {
            get {
                return ResourceManager.GetString("Code128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code39 ....
        /// </summary>
        internal static string Code39 {
            get {
                return ResourceManager.GetString("Code39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion from string to decimal overflowed..
        /// </summary>
        internal static string ConversionOverflowed {
            get {
                return ResourceManager.GetString("ConversionOverflowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoders ....
        /// </summary>
        internal static string Decoders {
            get {
                return ResourceManager.GetString("Decoders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLED.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOT.
        /// </summary>
        internal static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download the Company Information..
        /// </summary>
        internal static string DownloadCompanyInfo {
            get {
                return ResourceManager.GetString("DownloadCompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowloading files. Please wait....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download the Company Information..
        /// </summary>
        internal static string DownloadUserFile {
            get {
                return ResourceManager.GetString("DownloadUserFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLED.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your User ID.
        /// </summary>
        internal static string EnterID {
            get {
                return ResourceManager.GetString("EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your PIN.
        /// </summary>
        internal static string EnterPIN {
            get {
                return ResourceManager.GetString("EnterPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Qty Excessed.
        /// </summary>
        internal static string Excessed {
            get {
                return ResourceManager.GetString("Excessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Handy_Buttons {
            get {
                object obj = ResourceManager.GetObject("Handy_Buttons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon handy_icon_001 {
            get {
                object obj = ResourceManager.GetObject("handy_icon_001", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HandyFooter {
            get {
                object obj = ResourceManager.GetObject("HandyFooter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HandyHeader {
            get {
                object obj = ResourceManager.GetObject("HandyHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMED_HOLD.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitReader.
        /// </summary>
        internal static string InitReader {
            get {
                return ResourceManager.GetString("InitReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Barcode:.
        /// </summary>
        internal static string InvalidBC {
            get {
                return ResourceManager.GetString("InvalidBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Indexer.
        /// </summary>
        internal static string InvalidIndexer {
            get {
                return ResourceManager.GetString("InvalidIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        internal static string InvalidItem {
            get {
                return ResourceManager.GetString("InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN.
        /// </summary>
        internal static string InvalidPIN {
            get {
                return ResourceManager.GetString("InvalidPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not selected.
        /// </summary>
        internal static string ItemNotSelected {
            get {
                return ResourceManager.GetString("ItemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGGED ITEMS.
        /// </summary>
        internal static string ItemTag {
            get {
                return ResourceManager.GetString("ItemTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNTAGGED ITEMS.
        /// </summary>
        internal static string ItemUntag {
            get {
                return ResourceManager.GetString("ItemUntag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MMSLogo {
            get {
                object obj = ResourceManager.GetObject("MMSLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device Selected.
        /// </summary>
        internal static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is null..
        /// </summary>
        internal static string NullStirng {
            get {
                return ResourceManager.GetString("NullStirng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failure.
        /// </summary>
        internal static string OperationFailure {
            get {
                return ResourceManager.GetString("OperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options ....
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMED_RELEASE.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart scanning?.
        /// </summary>
        internal static string RestartScan {
            get {
                return ResourceManager.GetString("RestartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retag.
        /// </summary>
        internal static string Retag {
            get {
                return ResourceManager.GetString("Retag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETICLE.
        /// </summary>
        internal static string Reticle {
            get {
                return ResourceManager.GetString("Reticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID or PIN. Please try again..
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan ....
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Continuous ....
        /// </summary>
        internal static string ScanContinuous {
            get {
                return ResourceManager.GetString("ScanContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Scan exceed. Please move to the next Layer..
        /// </summary>
        internal static string ScanExceed {
            get {
                return ResourceManager.GetString("ScanExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Type ....
        /// </summary>
        internal static string ScanType {
            get {
                return ResourceManager.GetString("ScanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectDevice.
        /// </summary>
        internal static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in connecting to the Server..
        /// </summary>
        internal static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Signal_Excellent {
            get {
                object obj = ResourceManager.GetObject("Signal_Excellent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Signal_Fair {
            get {
                object obj = ResourceManager.GetObject("Signal_Fair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Signal_Good {
            get {
                object obj = ResourceManager.GetObject("Signal_Good", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Signal_None {
            get {
                object obj = ResourceManager.GetObject("Signal_None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Signal_Poor {
            get {
                object obj = ResourceManager.GetObject("Signal_Poor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Signal_VeryGood {
            get {
                object obj = ResourceManager.GetObject("Signal_VeryGood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLAB.
        /// </summary>
        internal static string Slab {
            get {
                return ResourceManager.GetString("Slab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartRead.
        /// </summary>
        internal static string StartRead {
            get {
                return ResourceManager.GetString("StartRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopRead.
        /// </summary>
        internal static string StopRead {
            get {
                return ResourceManager.GetString("StopRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is not formatted as a decimal..
        /// </summary>
        internal static string StringNotFormatted {
            get {
                return ResourceManager.GetString("StringNotFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermReader.
        /// </summary>
        internal static string TermReader {
            get {
                return ResourceManager.GetString("TermReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIGGER.
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untagged.
        /// </summary>
        internal static string Untag {
            get {
                return ResourceManager.GetString("Untag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #######################################################################
        ///
        ///# Directory    : 
        ///# Filename     : UpdateList.txt
        ///# Date Created : 1/08/2012 6:21:00 AM
        ///
        ///# Max Field(s) : 1
        ///
        ///# Split Char   : ,
        ///
        ///# FieldName(s) : Handy Files
        ///#######################################################################
        ///handy.dal.dll
        ///handy.lib.dll
        ///Handy V3.exe
        ///UpdateConfig.xml
        ///Handy Updater.exe.
        /// </summary>
        internal static string UpdateList {
            get {
                return ResourceManager.GetString("UpdateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
